-- the whole background is generated by a shader
function frame(t, layer)
  layer:effect("plasma", { speed = 0.8 })
  layer:effect("vignette", { amount = 0.7 })
  layer:effect("fade", { enter = 0.5, exit = 0.5 })
end
